<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: sans-serif; color: #333; }
        .header { border-bottom: 2px solid {{ $color }}; padding-bottom: 10px; margin-bottom: 20px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #999; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: {{ $color }}; color: white; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #eee; }
        .summary-box { background: #f9f9f9; padding: 15px; border-radius: 8px; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Utility Report</h1>
        <p>Tenant: {{ $user->name }} | Room: {{ $user->room_id }}</p>
    </div>

    <div class="summary-box">
        <h3>Summary of Last Month</h3>
        <p>Current Outstanding Balance: <strong>ZAR {{ number_format($user->room->totalCharges() ?? 0, 2) }}</strong></p> 
        <p>Water Usage: <strong>{{ $user->room->waterMeter->lastReading->consumption ?? 0 }} KL</strong></p>
        <p>Electricity Usage: <strong>{{ $user->room->electricityMeter->lastReading->consumption ?? 0 }} kWh</strong></p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Meter Serial</th>
                <th>Usage (KL/kWh)</th>
                <th>Cost (ZAR)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($readings as $i => $reading)
            
            @php
                // Find the charge created at the exact same time for this room
                $specificCharge = $reading->charge;
                
                if($i < $readings->count()-2){
                    // dd($readings->get($i-1));
                    $consumption = number_format($reading->consumption, 2) ?? $reading->reading_value - $readings->get($i + 2)->reading_value ?? 0;; // Calculate consumption based on current and previous reading
                }
            @endphp
            <tr>
                <td>{{ $reading->created_at->format('d M Y') }}</td>
                <td>{{ $reading->meter->serial_number ?? 'MTR-ROOM-02' }}</td>
                <td>{{ number_format($reading->consumption ?? $consumption, 2) }}</td>
                <td style="color: {{ $specificCharge ? ($specificCharge->is_paid == 0 ? 'red' : 'black') : '#333' }};">
                    ZAR {{ number_format($specificCharge->amount ?? 0, 2) }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by OPLANLA PMS on {{ $date }}
    </div>
</body>
</html>